Update Deps: Bumps React 18

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,6 +1,23 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
+# lint
 yarn run lint
+# lint --fix
 yarn run lint:fix
+# format code
 yarn run format
+# build
+yarn run build
+
+# test for last command executed
+if [ $? -eq 0 ]; then
+  # remove build extras
+  rm -rf public/sw.js public/sw.js.map public/workbox-*.js /.next
+  echo "Build Successful 😆!"
+  exit 0
+
+  else
+    echo "Oops! Build failed 😢."
+    exit 130
+fi
